# Generated by Django 5.2 on 2025-04-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="push",
            options={"verbose_name_plural": "Pushes"},
        ),
        migrations.AddField(
            model_name="page",
            name="is_remote",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unspec", "Unspecified"),
                    ("intern", "Intern"),
                    ("entry", "Entry-level"),
                    ("junior", "Junior"),
                    ("mid", "Mid-level"),
                    ("senior", "Senior"),
                    ("c_level", "C-level"),
                ],
                default="unspec",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="location",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="years_of_experience",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
