# Generated by Django 5.2 on 2025-04-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="selector",
            field=models.CharField(
                default="",
                help_text="CSS selector that selects all job titles in the page",
                max_length=128,
            ),
            preserve_default=False,
        ),
    ]
