# Generated by Django 5.2 on 2025-05-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_page_selector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="companies",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="pages",
            field=models.ManyToManyField(related_name="watchlists", to="core.page"),
        ),
    ]
