# Generated by Django 5.2 on 2025-07-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_watchlist_companies_watchlist_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
