# Generated by Django 5.2 on 2025-07-13 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_notification_options_notification_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="user",
            new_name="owner",
        ),
    ]
