# Generated by Django 5.2 on 2025-07-13 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_user_watchlist_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, related_name="watchlists", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_watchlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
