# Generated by Django 5.2 on 2025-07-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_watchlist_subscribers_alter_watchlist_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
