# Generated by Django 5.2 on 2025-07-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_watchlist_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-last_seen"]},
        ),
    ]
