# Generated by Django 5.2 on 2025-07-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_job_url_page_api_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="api_url",
            field=models.URLField(
                blank=True,
                help_text="If the response type is JSON, this is the URL to the API endpoint that returns the list of jobs. If the response type is HTML, this field is not used.",
                null=True,
            ),
        ),
    ]
