# Generated by Django 5.2 on 2025-08-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_page_api_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="job_url_key",
            field=models.CharField(
                blank=True,
                help_text="If the response type is JSON, this is a comma-separated list of keys that would give the job URL in a Job object in the JSON response.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="job_id_key",
            field=models.CharField(
                blank=True,
                help_text="If the response type is JSON, this is a comma-separated list of keys that would give the job ID in a Job object in the JSON response.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="title_key",
            field=models.CharField(
                blank=True,
                help_text="If the response type is JSON, this is a comma-separated list of keys that would give the job title in a Job object in the JSON response.",
                max_length=32,
                null=True,
            ),
        ),
    ]
