# Generated by Django 5.2 on 2025-08-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_page_job_url_key_alter_page_job_id_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="job_url_prefix",
            field=models.CharField(
                blank=True,
                help_text="If the response type is JSON and the job URL extracted from the job object is a relative URL, this prefix will be added to the job URL to make it absolute.",
                max_length=256,
                null=True,
            ),
        ),
    ]
