# Generated by Django 5.2 on 2025-08-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_page_job_url_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="selector",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If the response type is HTML, this is the CSS selector that selects all the job titles. If the response type is JSON, this is a comma-separated list of keys that would return the list of job titles from the JSON response.",
                max_length=128,
            ),
        ),
    ]
