# Generated by Django 5.2 on 2025-08-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_page_selector"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="request_method",
            field=models.CharField(
                blank=True,
                choices=[("GET", "GET"), ("POST", "POST"), ("PUT", "PUT")],
                default="GET",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="request_payload",
            field=models.JSONField(
                blank=True,
                default="",
                help_text="If the request method is POST or PUT, this is the payload that will be sent with the request.",
                null=True,
            ),
        ),
    ]
