# Generated by Django 5.2 on 2025-08-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_page_request_method_page_request_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
