# Generated by Django 5.2 on 2025-08-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="request_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="If the request method is POST or PUT, this is the payload that will be sent with the request.",
                null=True,
            ),
        ),
    ]
