# Generated by Django 5.2 on 2025-08-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_page_request_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="url",
            field=models.URLField(max_length=512),
        ),
    ]
