# Generated by Django 5.2 on 2025-09-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_page_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="push",
            options={"ordering": ["-time"], "verbose_name_plural": "Pushes"},
        ),
    ]
