# Generated by Django 5.2 on 2025-09-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_push_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="push",
            name="n_errors",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="push",
            name="n_jobs_found",
            field=models.IntegerField(default=0),
        ),
    ]
