# Generated by Django 5.2 on 2025-09-20 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_push_n_errors_push_n_jobs_found"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="push",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="core.push",
            ),
        ),
    ]
