# Generated by Django 5.2 on 2025-09-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_job_push"),
    ]

    operations = [
        migrations.AlterField(
            model_name="push",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
